### Q.1. Given an array a = np.array([10, 20, 30, 40, 50]) and an index array i = np.array([0, 1, 3]), use fancy indexing to extract elements and assign new values to them.

In [ ]:
import numpy as np

In [35]:
a = np.array([10, 20, 30, 40, 50]) 

# access diffrent place values using silicing method
print("a of 0:", a[0])
print("a of 1:",a[1])
print("a of 3:",a[3])

# assign random values at 0,1,3 position
a[0] = 3
a[1] = 60
a[3] = 70

print("\n new array:",a)

a of 0: 10
a of 1: 20
a of 3: 40

 new array: [ 3 60 30 70 50]


### Q. 2. Create a 4x4 matrix and compute the sum of all elements, the sum of each column, and the sum of each row.

In [95]:
arr0 = np.arange(16)
arr = arr0.reshape(4,4)

In [110]:
# addition of all eliment of the matrix

def add(sum):
    add = 0
    for i in sum:
        for j in i:
            add = add+j
    print(add)

add(arr)

120


In [163]:
# addition of each row elements of the matrix

def each_row(val):
    add = 0
    for i in val:
        for j in i:
            add = add+j
        print(f"addition of {i} is:",add)
each_row(arr)

addition of [0 1 2 3] is: 6
addition of [4 5 6 7] is: 28
addition of [ 8  9 10 11] is: 66
addition of [12 13 14 15] is: 120


In [177]:
# addition of each column elements of the matrix

def each_col(val):
    s = 1
    add = 0
    for i in range(len(val[0])):
        d = arr[:,i:s]
        for j in d:
            add = add+j
        print(f"addition of {d} is:",add)  
        s = s+1
    
each_col(arr)

addition of [[ 0]
 [ 4]
 [ 8]
 [12]] is: [24]
addition of [[ 1]
 [ 5]
 [ 9]
 [13]] is: [52]
addition of [[ 2]
 [ 6]
 [10]
 [14]] is: [84]
addition of [[ 3]
 [ 7]
 [11]
 [15]] is: [120]


### Q. 3. Given a 3-D array of shape (3, 4, 5), slice out a sub-array that contains the last two rows and columns of the last two matrices.

In [186]:
a = np.arange(60)
arr = a.reshape(3,4,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [248]:
# last two rows of the last two matrix

print("second last two row of last matrix: ","\n",arr[1,-1],"\n",arr[1,-2],"\n")
print("last two row of last matrix: \n",arr[-1,-1],"\n",arr[-1,-2],"\n")

second last two row of last matrix:  
 [35 36 37 38 39] 
 [30 31 32 33 34] 

last two row of last matrix: 
 [55 56 57 58 59] 
 [50 51 52 53 54] 



In [249]:
# # last two columns of the last two matrix

print("second last two row of last matrix: \n",arr[1][:,-1:],"\n\n",arr[-2][:,-2:-1])
print("\nlast two row of last matrix: \n",arr[-1][:,-1:],"\n\n",arr[-1][:,-2:-1])

second last two row of last matrix: 
 [[24]
 [29]
 [34]
 [39]] 

 [[23]
 [28]
 [33]
 [38]]

last two row of last matrix: 
 [[44]
 [49]
 [54]
 [59]] 

 [[43]
 [48]
 [53]
 [58]]
